[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
base64 = "0.22.1"
clap = { version = "4.5.40", features = ["derive"] }
nom = "8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
